apiVersion: v1
kind: ConfigMap
metadata:
  name: ${{ values.name }}-${{ values.owner }}
  labels:
    app: ${{ values.name }}-${{ values.owner }}
data:
  log.level: info
  service.name: "${{ values.name }}-${{ values.owner }}"