apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.name }}-${{ values.owner }}
  labels:
    app: ${{ values.name }}-${{ values.owner }}
    backstage.io/kubernetes-id: ${{ values.name }}-${{ values.owner }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.name }}-${{ values.owner }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ${{ values.name }}-${{ values.owner }}
        backstage.io/kubernetes-id: ${{ values.name }}-${{ values.owner }}
    spec:
      containers:
        - name: ${{ values.name }}-${{ values.owner }}
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "0.1"
              memory: 128Mi
          envFrom:
            - configmapRef: ${{ values.name }}-${{ values.owner }}