apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}-${{ values.owner }}
spec:
  selector:
    app: ${{ values.name }}-${{ values.owner }}
  ports:
    - port: 3000
      targetPort: 3000