apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: ${{values.description | dump}}
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: ${{ values.name }}-${{ values.owner }}
    backstage.io/kubernetes-namespace: ${{values.namespace}}
spec:
  type: service
  lifecycle: production
  owner: ${{values.owner | dump}}